language: node_js
node_js:
  - lts/*
cache: yarn
script:
  - yarn lint
  - yarn test
  - yarn coveralls
deploy:
  provider: npm
  email: dacurse0@gmail.com
  api_key:
    secure: Emw+w4/mWfWIq8kIAwd1cX+Ib9rmts1AvzVQjt1AFZFnvjgDlepnNDQIuXct0l6ujs8B2XFXs2godK2xG5ZH0OJIDl0goP3Z7/q4W3MYEzPCtqshOteaUU8q4rH68DMUpNyWVPRJ4cw9ERznlutpoFMHSWDSxgeP9i5uMbro09cg1Z11B9FtvphM5q/uJCZ0Pxvk9HMVXG8fRmWt1m9X9s8jnRBBUdJ0rJB+jQE5kgRhGt0obfUFSLGQEj5bavOMyOgoJpmeLkBTv0afg+d5LipYn1Ue5d/ePkGT64WAyakjgLhYDe4Fp7ZsFlbjKZrHDeAiJ+ke6V3iDPIojN0voPO+ngvsrtY4BdcrJmScesJ7zAT7m5P6ZiF7k4bWLAWkOLn764sgJa4bDRi55XVLOl9BMgC6Il9FqSkVGCEzGAtKJL54AMKRDJH0cvR9djmyRZuEjjE3tkVNANnWyoQ9/Zz0ykXyVLAkEoPWVoce8bOIgyIXzb+klcmwckDAL8D6FrFxNqn9smh/47NMRPX7ZaDHirFG//Hoj+zfP+cI358xWLkuLb4yFeZkX71UvhFkyRPgdZHVA6yLxnJeYU40nFcD3AcJzvdJulTEpBECdl3Q6E3Ez5H4oMkqoDT/y9bEhOxHRHk9etXGqu40H5x+RvYtoFxiW5yGfVtauBXgdjQ=
  on:
    tags: true
    repo: DaCurse/boilerplator
  skip_cleanup: 'true'
