language: node_js
node_js:
  - lts/*
cache: yarn
script:
  - yarn test
  - yarn coveralls
deploy:
  provider: npm
  email: dacurse0@gmail.com
  api_key:
    secure: Kl+Sczkb5YQoE/kCm3llMjUKSoUBWibJnOk/lRNFR2kdc2Y776JZ+ocj2rSDvjtdqBspzy5K6slO6f174JHW9MrMuuh2b1GRqQiSHFIclAcrNRLlZ1DioGoxgdvMd0wWA3K1o7UrWAnZf7B0NxUOCxC5G8BhCYpKSCodItgrmyxkH1Fuj2tXl/8JfBGEEJBrI/v4rikWmS+7Doto6RScQlNTREM629M1E+ajie5xgeYz00uv56AMWukPic/BcO3cFrsmMlaf4M4VyXij8ORM5nE/jgriL4C+IxnIC+eI1En4ujDJH5doh9pkPGnVIagQsTSKdkaSWQwx9j/xyxsdNebcJ5ELdXTJ0KOxYObpxlrO6UBwyQXrGVbyVIcAzE+zCE55GYQjOBSWP2PSDTevQZjlBQ1IRQGO3tKTM21NEjnczeLTz9HXH2TKt4WflISD/4ZOG37Ju5GYuwWGBN/LqNLBmt2zRwiqFsui9FVB4lG0C1BDeOWYNCTncE6ZvK4L4haZ9T6Eo/F6wAv/nm4RaHPVfGdPLYeEcnn4FX9TkWhBPtfiN8ojeo8ICrRIFEXfjuiYUyKt3RSGrQ2n0BuYkDZoxRRKW3QMIAG0Fw/QW0ITRlQsCtz5/nlw4YIyK0Yx87ty3RLYjmc+QrGxtrIDh5EEHCGryr2bXIDqv6Haqdc=
  on:
    tags: true
    repo: DaCurse/boilerplator
  skip_cleanup: 'true'
